### importing libraries additional setup

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path
import warnings

In [ ]:
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

### Data loading

In [70]:
full_path = Path("../data")
path = full_path / "cars.csv"
data = pd.read_csv(path);

### Overlooking

In [71]:
data = data.sample(50_000, random_state=42)

In [72]:
data.head()

,id_x,car_rel_url_x,datetime_scrape,name,price_x,currency_x,datetime_product,city,day,hour,attributes,production_year,engine_displacement_num,engine_displacement_unit,kilometrage_num,kilometrage_unit,barter,loan,salon,spare_parts,vip,featured,img_url,id_y,cars_id,car_rel_url_y,datetime,description,price_y,currency_y,owner_name,shop_name,phone,updated,views,vin,car_details_id_x,Ban növü,Buraxılış ili,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Qəzalı,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Yürüş,Ötürücü,Şəhər,car_details_id_y,car_rel_url,extra_info
251032,2f265aa7-2a78-4e10-9c66-4ee6dd17ef19,/autos/8847270-bmw-x5,2024-10-18 23:30:09.058641+00,BMW X5,39000.0,AZN,"Bakı, dünən 10:16",bakı,18.10.2024,10:16,"2013, 3.0 L, 229 000 km",2013,3.0,L,229000,km,Barter mümkündür,Kreditdədir,Salon,NaN,NaN,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,a9144bd6-6b48-4bbb-8cae-35f0b99356f1,2f265aa7-2a78-4e10-9c66-4ee6dd17ef19,/autos/8847270-bmw-x5,2024-10-18 23:34:16.967962+00,12.500 AZN VER APAR ! ! !\n-------------------...,39000.0,AZN,NaN,Otogallery by Pegasus Auto,772236363.0,18.10.2024,855,NaN,a9144bd6-6b48-4bbb-8cae-35f0b99356f1,"Offroader / SUV, 5 qapı",2013,Avropa,BMW,X5,3.0 L/306 a.g./Benzin,NaN,Qara,NaN,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,229 000 km,Tam,Bakı,a9144bd6-6b48-4bbb-8cae-35f0b99356f1,/autos/8847270-bmw-x5,Yüngül lehimli disklər* ABS* Lyuk* Yağış senso...
33984,65ee383a-efde-4460-892c-e126870e7f00,/autos/8704798-nissan-kicks,2024-09-17 20:32:32.584013+00,Nissan Kicks,27000.0,AZN,"Bakı, dünən 08:34",bakı,17.09.2024,08:34,"2018, 1.6 L, 76 000 km",2018,1.6,L,76000,km,Barter mümkündür,NaN,Salon,NaN,NaN,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,95d952b5-ed23-4974-9738-76b3cf957a24,65ee383a-efde-4460-892c-e126870e7f00,/autos/8704798-nissan-kicks,2024-09-17 20:58:07.020496+00,Buraxilis ili 2018\n,27000.0,AZN,NaN,Cənub Avto,505555542.0,17.09.2024,264,NaN,95d952b5-ed23-4974-9738-76b3cf957a24,"Offroader / SUV, 5 qapı",2018,Amerika,Nissan,Kicks,1.6 L/125 a.g./Benzin,NaN,Ağ,0,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,76 000 km,Ön,Bakı,95d952b5-ed23-4974-9738-76b3cf957a24,/autos/8704798-nissan-kicks,Yüngül lehimli disklər* ABS* Yağış sensoru* Mə...
492928,a4d90028-b25a-4e9e-aa42-2ef04d87ed4e,/autos/8925283-changan-cs-95,2024-11-21 20:15:07.490559,Changan CS 95,65900.0,AZN,"Bakı, dünən 09:54",bakı,21.11.2024,09:54,"2024, 2.0 L, 0 km",2024,2.0,L,0,km,Barter mümkündür,Kreditdədir,Salon,NaN,vipped-icon,featured-icon,https://turbo.azstatic.com/uploads/f460x343/20...,80d5e8d3-9b2b-483e-a96f-a5c474d92b1a,a4d90028-b25a-4e9e-aa42-2ef04d87ed4e,/autos/8925283-changan-cs-95,2024-11-21 20:21:21.748712,CHANGAN-nın Azərbaycandakı rəsmi distributoru ...,65900.0,AZN,NaN,Changan Azerbaijan,512014930.0,21.11.2024,4369,NaN,80d5e8d3-9b2b-483e-a96f-a5c474d92b1a,"Offroader / SUV, 5 qapı",2024,NaN,Changan,CS 95,2.0 L / 233 a.g. / Benzin,NaN,Qara,NaN,Avtomat,"Vuruğu yoxdur, rənglənməyib",Bəli,7,0 km,Tam,Bakı,80d5e8d3-9b2b-483e-a96f-a5c474d92b1a,/autos/8925283-changan-cs-95,Yüngül lehimli disklər* ABS* Lyuk* Yağış senso...
108882,6d662148-11c0-4f99-a1cd-aa4f8a983832,/autos/8823045-mercedes-vito,2024-09-29 20:29:52.171123+00,Mercedes Vito,11500.0,AZN,"Gəncə, dünən 15:48",gəncə,29.09.2024,15:48,"1997, 2.3 L, 850 000 km",1997,2.3,L,850000,km,NaN,NaN,NaN,NaN,NaN,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,ac4d6965-2b15-4f06-a74b-d14dbb5ab355,6d662148-11c0-4f99-a1cd-aa4f8a983832,/autos/8823045-mercedes-vito,2024-09-29 20:44:31.452137+00,"{""Salam aleykum. Heç bir problemi yoxdur. Hər ...",11500.0,AZN,Rəşid,NaN,709334756.0,29.09.2024,308,NaN,ac4d6965-2b15-4f06-a74b-d14dbb5ab355,Minivan,1997,Avropa,Mercedes,Vito,2.3 L/98 a.g./Dizel,NaN,Qırmızı,NaN,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,8+,850 000 km,Ön,Gəncə,ac4d6965-2b15-4f06-a74b-d14dbb5ab355,/autos/8823045-mercedes-vito,Kondisioner
130246,4a1d378d-c5bc-4834-a2a1-3e19b3f4fd21,/autos/8679836-hyundai-sonata,2024-10-02 21:20:55.197043+00,Hyundai Sonata,29500.0,AZN,"Bakı, dünən 16:50",bakı,02.10.2024,16:50,"2017, 2.0 L, 131 000 km",2017,2.0,L,131000,km,Barter mümkündür,Kreditdədir,Salon,NaN,NaN,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,26becf77-6cf9-4296-a495-e03f05395a93,4a1d378d-c5bc-4834-a2a1-3e19b3f4fd21,/autos/8679836-hyundai-sonata,2024-10-02 21:26:48.633134+00,"{""MÖHTƏŞƏM KREDİT KAMPANİYASI!\n"",""İndi bu avt...",29500.0,AZN,NaN,CarPro,512444120.0,02.10.2024,4238,NaN,26becf77-6cf9-4296-a495-e03f05395a93,Sedan,2017,Koreya,Hyundai,Sonata,2.0 L/245 a.g./Benzin,NaN,Ağ,NaN,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,131 000 km,Ön,Bakı,26becf77-6cf9-4296-a495-e03f05395a93,/autos/8679836-hyundai-sonata,Yüngül lehimli disklər* ABS* Yağış sensoru* Mə...

In [77]:
data.describe(include="all")

,id_x,car_rel_url_x,datetime_scrape,name,price_x,currency_x,datetime_product,city,day,hour,attributes,production_year,engine_displacement_num,engine_displacement_unit,kilometrage_num,kilometrage_unit,barter,loan,salon,spare_parts,vip,featured,img_url,id_y,cars_id,car_rel_url_y,datetime,description,price_y,currency_y,owner_name,shop_name,phone,updated,views,vin,car_details_id_x,Ban növü,Buraxılış ili,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Qəzalı,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Yürüş,Ötürücü,Şəhər,car_details_id_y,car_rel_url,extra_info
count,50000,50000,50000,50000,50000.00000,50000,50000,50000,50000,50000,50000,50000.000000,50000.000000,49529,5.000000e+04,49529,17120,12347,14600,137,22359,12668,50000,50000,50000,50000,50000,48884,50000.000000,50000,34879,15105,4.998400e+04,50000,50000.000000,3397,50000,50000,50000.000000,35476,50000,50000,50000,137,50000,33049,50000,50000,50000,37282,50000,50000,50000,50000,50000,50000
unique,49969,31954,93,1565,NaN,3,6271,66,92,1323,24219,NaN,NaN,1,NaN,1,1,1,1,1,1,1,32999,50000,49969,31954,212,34551,NaN,3,3734,308,NaN,100,NaN,2210,50000,33,NaN,9,153,1529,3664,1,18,5,5,4,2,8,7913,3,66,50000,31954,2064
top,7309709a-91e5-4506-9734-4c723e1185db,/autos/8623937-land-rover-rr-sport,2024-10-04 21:12:26.805359+00,Kia Sorento,NaN,AZN,"Bakı, dünən 11:30",bakı,04.10.2024,11:30,"2024, 1.5 L, 0 km",NaN,NaN,L,NaN,km,Barter mümkündür,Kreditdədir,Salon,Qəzalı,vipped-icon,featured-icon,https://turbo.azstatic.com/uploads/f460x343/20...,be49a628-2eae-47f0-b3a7-4fb97865f806,7309709a-91e5-4506-9734-4c723e1185db,/autos/8623937-land-rover-rr-sport,2024-11-25 20:21:39.009696,{},NaN,AZN,Sahib,AvtoExpress Baku,NaN,04.10.2024,NaN,WAUZZZ4M4GD022274,be49a628-2eae-47f0-b3a7-4fb97865f806,Sedan,NaN,Rəsmi diler,Mercedes,Sorento,2.0 L/184 a.g./Dizel,Bəli,Ağ,1,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,0 km,Ön,Bakı,be49a628-2eae-47f0-b3a7-4fb97865f806,/autos/8623937-land-rover-rr-sport,Yüngül lehimli disklər* ABS* Lyuk* Yağış senso...
freq,2,13,844,1735,NaN,35550,102,41219,989,120,1863,NaN,NaN,49529,NaN,49529,17120,12347,14600,137,22359,12668,13,1,2,13,633,259,NaN,35549,783,532,NaN,997,NaN,10,1,21127,NaN,9092,6869,1735,1497,137,15647,15809,35818,47058,43279,27044,6686,24323,41219,1,13,11238
mean,NaN,NaN,NaN,NaN,31687.84212,NaN,NaN,NaN,NaN,NaN,NaN,1994.788560,2.215674,NaN,1.551148e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31687.940120,NaN,NaN,NaN,5.595961e+08,NaN,3758.766060,NaN,NaN,NaN,2013.844600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,28888.40487,NaN,NaN,NaN,NaN,NaN,NaN,194.674935,1.260224,NaN,1.342809e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28888.440528,NaN,NaN,NaN,1.515495e+08,NaN,10133.717764,NaN,NaN,NaN,7.619875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,900.00000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,900.000000,NaN,NaN,NaN,7.800000e+01,NaN,17.000000,NaN,NaN,NaN,1954.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,16800.00000,NaN,NaN,NaN,NaN,NaN,NaN,2009.000000,1.600000,NaN,5.500000e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16800.000000,NaN,NaN,NaN,5.060000e+08,NaN,439.000000,NaN,NaN,NaN,2009.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,25400.00000,NaN,NaN,NaN,NaN,NaN,NaN,2015.000000,2.000000,NaN,1.430000e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25400.000000,NaN,NaN,NaN,5.524103e+08,NaN,1376.000000,NaN,NaN,NaN,2015.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,36800.00000,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,2.500000,NaN,2.220000e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36800.000000,NaN,NaN,NaN,5.589859e+08,NaN,3446.000000,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,940000.00000,NaN,NaN,NaN,NaN,NaN,NaN,2024.000000,120.000000,NaN,3.270000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,940000.000000,NaN,NaN,NaN,9.999996e+08,NaN,327443.000000,NaN,NaN,NaN,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Dropping some values and Select values that we need

In [261]:
df = data
df = df.drop_duplicates(["car_rel_url_x"], keep="first")

In [262]:
df = df[["Marka", "Model","city", "price_x", "currency_x", "production_year", "engine_displacement_num", "engine_displacement_unit", "kilometrage_num", "kilometrage_unit", "barter", "loan", "Qəzalı", "Rəng", "Sahiblər", "Vəziyyəti", "Yeni", "Ötürücü", "Mühərrik", "Yerlərin sayı", "Sürətlər qutusu", "Ban növü"]]

In [263]:
df.shape

(31939, 22)

In [264]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31939 entries, 251032 to 420538
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Marka                     31939 non-null  object
 1   Model                     31939 non-null  object
 2   city                      31939 non-null  object
 3   price_x                   31939 non-null  float64
 4   currency_x                31939 non-null  object
 5   production_year           31939 non-null  int64
 6   engine_displacement_num   31939 non-null  float64
 7   engine_displacement_unit  31742 non-null  object
 8   kilometrage_num           31939 non-null  int64
 9   kilometrage_unit          31742 non-null  object
 10  barter                    9803 non-null   object
 11  loan                      6861 non-null   object
 12  Qəzalı                    120 non-null    object
 13  Rəng                      31939 non-null  object
 14  Sahiblər                  21932 non-null  object
 15  Vəziyyəti                 31939 non-null  object
 16  Yeni                      31939 non-null  object
 17  Ötürücü                   31939 non-null  object
 18  Mühərrik                  31939 non-null  object
 19  Yerlərin sayı             23915 non-null  object
 20  Sürətlər qutusu           31939 non-null  object
 21  Ban növü                  31939 non-null  object
dtypes: float64(2), int64(2), object(18)
memory usage: 5.6+ MB

In [265]:
[(item,df[item].isna().sum()) for item in df.columns if df[item].isna().sum() != 0]

[('engine_displacement_unit', np.int64(197)),
 ('kilometrage_unit', np.int64(197)),
 ('barter', np.int64(22136)),
 ('loan', np.int64(25078)),
 ('Qəzalı', np.int64(31819)),
 ('Sahiblər', np.int64(10007)),
 ('Yerlərin sayı', np.int64(8024))]

### Data egnineering

In [266]:
# converting currencies
df["currency_x"].value_counts()

currency_x
AZN    24648
$       7134
€        157
Name: count, dtype: int64

In [267]:
# converting all currencies to azn
dollar = df.loc[df["currency_x"] == "$", "price_x"]
euro = df.loc[df["currency_x"] == "€", "price_x"]

df.loc[df["currency_x"] == "$", "price_x"] = dollar * 1.7
df.loc[df["currency_x"] == "€", "price_x"] = euro * 1.8

In [268]:
# some values is nan
df["engine_displacement_unit"].isna().value_counts()

engine_displacement_unit
False    31742
True       197
Name: count, dtype: int64

In [269]:
# only electros has no Litr paramter
df["Mühərrik"].str.split("/", expand=True)[2].value_counts()

2
Benzin             13325
 Benzin             6959
Dizel               4910
 Dizel              2626
Hibrid              1519
 Hibrid              995
Plug-in Hibrid       561
 Plug-in Hibrid      505
Elektro              322
Qaz                   11
 Qaz                   9
Name: count, dtype: int64

In [270]:
df.loc[df["engine_displacement_unit"].isna(), "engine_displacement_num"]

504299    0.0
507612    0.0
469068    0.0
488057    0.0
631707    0.0
         ...
495373    0.0
555947    0.0
554804    0.0
542206    0.0
560600    0.0
Name: engine_displacement_num, Length: 197, dtype: float64

In [271]:
# selecting every a.g values
engine_parsed = df["Mühərrik"].str.split("/", expand=True)

engine_ag = pd.DataFrame(np.where((engine_parsed.iloc[::, -2] == " Elektro"), engine_parsed[0], engine_parsed[1]), index=df["Mühərrik"].index)

df["Hourse Power"] = engine_ag[0].str.split("a.g.", expand=True)[0].astype(int)

In [272]:
# selecting every fuel type values
engine_fuel_type = np.where((engine_parsed.iloc[::, -2] == " Elektro"), engine_parsed[1], engine_parsed[2])
engine_fuel_type = [i.split(" ")[-1] for i in engine_fuel_type]
df["Fuel Type"] = pd.DataFrame(engine_fuel_type, index=df["Mühərrik"].index)

In [273]:
# there is only kimoterage unit is NA is where kiolemtrage number is 0
df.loc[df["kilometrage_unit"].isna(), "kilometrage_num"].value_counts()

kilometrage_num
0    197
Name: count, dtype: int64

In [274]:
df.loc[df["Sahiblər"]=="4 və daha çox", "Sahiblər"] = 4
df.loc[df["Sahiblər"]==0, "Sahiblər"] = 1

In [275]:
df["barter"] = df["barter"].fillna("Barter mümkün deyil")
df["loan"] = df["loan"].fillna("Kreditdə deyil")
df["Qəzalı"] = df["Qəzalı"].fillna("Xeyr")
df["Sahiblər"] = df["Sahiblər"].fillna(df["Sahiblər"].median())

In [276]:
df["Sahiblər"] = df["Sahiblər"].astype(int)

In [277]:
df["kilometrage_unit"].value_counts()

kilometrage_unit
km    31742
Name: count, dtype: int64

In [278]:
df["barter"].value_counts()

barter
Barter mümkün deyil    22136
Barter mümkündür        9803
Name: count, dtype: int64

In [279]:
df.loc[df["Yerlərin sayı"]=="8+", "Yerlərin sayı"] = 8
df["Yerlərin sayı"] = df["Yerlərin sayı"].fillna(df["Yerlərin sayı"].median())
df["Yerlərin sayı"] = df["Yerlərin sayı"].astype("int")

In [280]:
df

             Marka        Model       city   price_x currency_x  production_year  engine_displacement_num engine_displacement_unit  kilometrage_num kilometrage_unit               barter            loan Qəzalı        Rəng  Sahiblər                    Vəziyyəti  Yeni Ötürücü                   Mühərrik  Yerlərin sayı Sürətlər qutusu                 Ban növü  Hourse Power Fuel Type
251032         BMW           X5       bakı   39000.0        AZN             2013                      3.0                        L           229000               km     Barter mümkündür     Kreditdədir   Xeyr        Qara         1  Vuruğu yoxdur, rənglənməyib  Xeyr     Tam      3.0 L/306 a.g./Benzin              5         Avtomat  Offroader / SUV, 5 qapı           306    Benzin
33984       Nissan        Kicks       bakı   27000.0        AZN             2018                      1.6                        L            76000               km     Barter mümkündür  Kreditdə deyil   Xeyr          Ağ         0  Vuruğu yoxdur, rənglənməyib  Xeyr      Ön      1.6 L/125 a.g./Benzin              5        Variator  Offroader / SUV, 5 qapı           125    Benzin
492928     Changan        CS 95       bakı   65900.0        AZN             2024                      2.0                        L                0               km     Barter mümkündür     Kreditdədir   Xeyr        Qara         1  Vuruğu yoxdur, rənglənməyib  Bəli     Tam  2.0 L / 233 a.g. / Benzin              7         Avtomat  Offroader / SUV, 5 qapı           233    Benzin
108882    Mercedes         Vito      gəncə   11500.0        AZN             1997                      2.3                        L           850000               km  Barter mümkün deyil  Kreditdə deyil   Xeyr     Qırmızı         1  Vuruğu yoxdur, rənglənməyib  Xeyr      Ön        2.3 L/98 a.g./Dizel              8        Mexaniki                  Minivan            98     Dizel
130246     Hyundai       Sonata       bakı   29500.0        AZN             2017                      2.0                        L           131000               km     Barter mümkündür     Kreditdədir   Xeyr          Ağ         1  Vuruğu yoxdur, rənglənməyib  Xeyr      Ön      2.0 L/245 a.g./Benzin              5         Avtomat                    Sedan           245    Benzin
...            ...          ...        ...       ...        ...              ...                      ...                      ...              ...              ...                  ...             ...    ...         ...       ...                          ...   ...     ...                        ...            ...             ...                      ...           ...       ...
585968  Land Rover  Range Rover       bakı  324360.0          $             2024                      3.0                        L                0               km     Barter mümkündür     Kreditdədir   Xeyr        Qara         1  Vuruğu yoxdur, rənglənməyib  Bəli     Tam   3.0 L / 300 a.g. / Dizel              5         Avtomat  Offroader / SUV, 5 qapı           300     Dizel
335971    Mercedes        C 220       bakı    8400.0        AZN             1996                      2.2                        L           315258               km  Barter mümkün deyil  Kreditdə deyil   Xeyr  Yaş Asfalt         2  Vuruğu yoxdur, rənglənməyib  Xeyr    Arxa      2.2 L/150 a.g./Benzin              4         Avtomat                    Sedan           150    Benzin
501476         Kia      Sorento       bakı   40000.0        AZN             2017                      2.0                        L           148000               km  Barter mümkün deyil  Kreditdə deyil   Xeyr          Ağ         1  Vuruğu yoxdur, rənglənməyib  Xeyr      Ön   2.0 L / 184 a.g. / Dizel              5         Avtomat  Offroader / SUV, 5 qapı           184     Dizel
300696    Mercedes        E 320   sumqayıt   18900.0        AZN             2000                      3.2                        L           371000               km  Barter mümkün deyil  Kreditdə deyil   Xeyr      Gümüşü         2  Vuruğu yoxdur, rənglənməyib  Xeyr    Arxa      3.2 L/224 a.g./Benzin              5         Avtomat                    Sedan           224    Benzin
420538  LADA (VAZ)       Priora  biləsuvar   12000.0        AZN             2012                      1.6                        L           230000               km  Barter mümkün deyil  Kreditdə deyil   Xeyr          Ağ         1  Vuruğu yoxdur, rənglənməyib  Xeyr      Ön      1.6 L/100 a.g./Benzin              5        Mexaniki                    Sedan           100    Benzin

[31939 rows x 24 columns]

### Showing corelations